spring:
  datasource:
    url: jdbc:vertica://219.131.193.214:5433/vertica
    username: dbadmin
    password: 123456
    driverClassName: com.vertica.jdbc.Driver

  jpa:
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: update
        hbm2ddl:
          import_files: