spring:
  datasource:
    url: jdbc:vertica://219.131.193.214:5433/vertica
    username: dbadmin
    password: 123456
    driverClassName: com.vertica.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: update
        hbm2ddl:
          import_files:

  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.web: ERROR
    com.creawor.sales: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: F:/Logger/debug_sales.log

sales:
  files:
    folder: F:/Logger
